name: bestieai
description: BestieAI - AI Chat, Tools & Earnings
version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  speech_to_text: ^6.3.0
  file_picker: ^5.3.3
  google_mobile_ads: ^2.3.0
  upi_india: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
